// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB23Nq6ihv5Ioo-FtOeylu14mhtT3_Mwao',
    appId: '1:649591134192:web:86aada2a480d2606856f35',
    messagingSenderId: '649591134192',
    projectId: 'medibound-428805',
    authDomain: 'medibound-428805.firebaseapp.com',
    storageBucket: 'medibound-428805.appspot.com',
    measurementId: 'G-2SN3LDEK5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvOQS4Nc3y19ZFx2RGQk9EFhr5tpeRKm0',
    appId: '1:46115585123:android:18f4eeda820e5236578c56',
    messagingSenderId: '46115585123',
    projectId: 'medibound-420121',
    storageBucket: 'medibound-420121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_r2OoyCmRAR-t7-pC4kop7cLiq1BO8W0',
    appId: '1:46115585123:ios:542d6234c32b5b25578c56',
    messagingSenderId: '46115585123',
    projectId: 'medibound-420121',
    storageBucket: 'medibound-420121.appspot.com',
    iosBundleId: 'com.example.mediboundbusiness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClV083ZIIfk6YqXXBIlfNT3PupRAjRyKU',
    appId: '1:649591134192:ios:3c156900a4883e9f856f35',
    messagingSenderId: '649591134192',
    projectId: 'medibound-428805',
    storageBucket: 'medibound-428805.appspot.com',
    iosBundleId: 'com.example.mediboundbusiness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB23Nq6ihv5Ioo-FtOeylu14mhtT3_Mwao',
    appId: '1:649591134192:web:9dd933d617cbb7fa856f35',
    messagingSenderId: '649591134192',
    projectId: 'medibound-428805',
    authDomain: 'medibound-428805.firebaseapp.com',
    storageBucket: 'medibound-428805.appspot.com',
    measurementId: 'G-T97V9XZYQ6',
  );

}